package eu.fbk.st.cryptoac

import kotlinx.serialization.Serializable

/**
 * Codes for describing the outcome of any operation in CryptoAC.
 * If none of these codes is suitable to describe the outcome of
 * a new operation, document and add a new code.
 */
@Serializable
enum class OutcomeCode {
    CODE_000_SUCCESS,
    
    CODE_001_USER_ALREADY_EXISTS,
    CODE_002_ROLE_ALREADY_EXISTS,
    CODE_003_FILE_ALREADY_EXISTS,
    
    CODE_004_USER_NOT_FOUND,
    CODE_005_ROLE_NOT_FOUND,
    CODE_006_FILE_NOT_FOUND,

    CODE_007_ROLETUPLE_NOT_FOUND,
    CODE_008_PERMISSIONTUPLE_NOT_FOUND,
    CODE_009_FILETUPLE_NOT_FOUND,

    CODE_010_ROLETUPLE_ALREADY_EXISTS,
    CODE_011_PERMISSIONTUPLE_ALREADY_EXISTS,
    CODE_012_FILETUPLE_ALREADY_EXISTS,

    CODE_013_USER_WAS_DELETED,
    CODE_014_ROLE_WAS_DELETED,
    CODE_015_FILE_WAS_DELETED,

    CODE_016_INVALID_PERMISSION,
    CODE_017_INVALID_VERSION_NUMBER,

    CODE_018_INTERFACE_CONFIGURATION_PARAMETERS,
    CODE_019_MISSING_PARAMETERS,
    CODE_020_INVALID_PARAMETER,
    CODE_021_RM_CONFIGURATION,

    CODE_022_ADMIN_CANNOT_BE_MODIFIED,
    CODE_023_USER_CANNOT_BE_MODIFIED,

    CODE_024_FILE_DELETE,
    CODE_025_FILE_RENAMING,

    CODE_026_TUPLE_FORMAT,
    CODE_027_AC_ENFORCEMENT_INCONSISTENT,

    CODE_028_OPA_POLICY_CREATION,
    CODE_029_OPA_DOCUMENT_UPDATE,
    CODE_030_OPA_DOCUMENT_DOWNLOAD,

    CODE_031_LOCK_CALLED_IN_INCONSISTENT_STATUS,
    CODE_032_UNLOCK_CALLED_IN_INCONSISTENT_STATUS,
    CODE_033_ROLLBACK_CALLED_IN_INCONSISTENT_STATUS,

    CODE_034_ADMIN_ALREADY_INITIALIZED,

    CODE_035_FORBIDDEN,
    CODE_036_UNAUTHORIZED,

    CODE_037_USER_DOES_NOT_EXIST_OR_WAS_NOT_INITIALIZED_OR_WAS_DELETED,

    CODE_038_PROFILE_NOT_FOUND,
    CODE_039_MALFORMED_PROFILE_FILE,

    CODE_040_UR_ASSIGNMENTS_NOT_FOUND,
    CODE_041_PA_ASSIGNMENTS_NOT_FOUND,

    CODE_042_RM_CONNECTION_TIMEOUT,
    CODE_043_DS_CONNECTION_TIMEOUT,
    CODE_044_MS_CONNECTION_TIMEOUT,
    CODE_045_PROXY_CONNECTION_TIMEOUT,

    CODE_046_HTTP_METHOD_NOT_SUPPORTED,

    CODE_047_UNEXPECTED,

    CODE_048_USER_OR_ROLE_NOT_FOUND_OR_ROLETUPLE_ALREADY_EXISTS,
    CODE_049_ROLE_OR_FILE_NOT_FOUND_OR_PERMISSIONTUPLE_ALREADY_EXISTS,
    CODE_050_FILE_NOT_FOUND_OR_FILETUPLE_ALREADY_EXISTS,

    CODE_051_NO_NEW_MESSAGES_TO_READ,

    CODE_052_FUNCTIONALITY_UNDER_CONSTRUCTION,
}