package eu.fbk.st.cryptoac

import kotlinx.serialization.*

/**
 * Codes for describing the outcome of any operation in CryptoAC.
 * A code is composed of the keyword "CODE", the error number and
 * an error message, separated by the underscore "_" character.
 * If none of these codes is suitable to describe the outcome of
 * a new operation, document and add a new code
 */
@Serializable
enum class OutcomeCode {
    CODE_000_SUCCESS,

    CODE_001_USER_ALREADY_EXISTS,
    CODE_002_ROLE_ALREADY_EXISTS,
    CODE_003_RESOURCE_ALREADY_EXISTS,

    CODE_004_USER_NOT_FOUND,
    CODE_005_ROLE_NOT_FOUND,
    CODE_006_RESOURCE_NOT_FOUND,

    CODE_007_ROLETUPLE_NOT_FOUND,
    CODE_008_PERMISSIONTUPLE_NOT_FOUND,
    // TODO 009 free

    CODE_010_ROLETUPLE_ALREADY_EXISTS,
    CODE_011_PERMISSIONTUPLE_ALREADY_EXISTS,

    // TODO 012 free

    CODE_013_USER_WAS_DELETED,
    CODE_014_ROLE_WAS_DELETED,
    CODE_015_RESOURCE_WAS_DELETED,

    CODE_016_INVALID_PERMISSION,
    CODE_017_INVALID_VERSION_NUMBER,

    CODE_018_SERVICE_CONFIGURATION_PARAMETERS,
    CODE_019_MISSING_PARAMETERS,
    CODE_020_INVALID_PARAMETER,
    CODE_021_RM_CONFIGURATION,

    CODE_022_ADMIN_CANNOT_BE_MODIFIED,
    CODE_023_USER_CANNOT_BE_MODIFIED,

    CODE_024_RESOURCE_DELETE,
    CODE_025_RESOURCE_WRITE,

    CODE_026_TUPLE_FORMAT,
    CODE_027_AC_ENFORCEMENT_INCONSISTENT,

    CODE_028_OPA_POLICY_CREATION,
    CODE_029_OPA_POLICY_UPDATE,
    CODE_030_OPA_DOCUMENT_DOWNLOAD,

    CODE_031_LOCK_CALLED_IN_INCONSISTENT_STATUS,
    CODE_032_UNLOCK_CALLED_IN_INCONSISTENT_STATUS,
    CODE_033_ROLLBACK_CALLED_IN_INCONSISTENT_STATUS,
    CODE_034_UNLOCK_FAILED,

    CODE_035_ADMIN_ALREADY_INITIALIZED,
    CODE_036_ADMIN_NAME,

    CODE_037_FORBIDDEN,
    CODE_038_UNAUTHORIZED,

    CODE_039_PROFILE_NOT_FOUND,
    CODE_040_MALFORMED_PROFILE,

    CODE_041_UR_ASSIGNMENTS_NOT_FOUND,
    CODE_042_PA_ASSIGNMENTS_NOT_FOUND,

    CODE_043_RM_CONNECTION_TIMEOUT,
    CODE_044_DM_CONNECTION_TIMEOUT,
    CODE_045_MM_CONNECTION_TIMEOUT,
    CODE_046_CRYPTOAC_CONNECTION_TIMEOUT,
    CODE_047_AC_CONNECTION_TIMEOUT,

    CODE_048_HTTP_METHOD_NOT_SUPPORTED,

    CODE_049_UNEXPECTED,

    CODE_050_FUNCTIONALITY_UNDER_CONSTRUCTION,

    CODE_051_LOGIN_REQUIRED,

    CODE_052_USER_ALREADY_INITIALIZED,
    CODE_053_USER_IS_INCOMPLETE,

    CODE_054_CREATE_USER_MM,
    CODE_055_ACCESS_DENIED_TO_MM,
    CODE_056_DELETE_USER_MM,

    CODE_057_SERVICE_TYPE_UPDATED,

    CODE_058_INCONSISTENT_STATUS_DELETE_TEMPORARY_RESOURCE_IN_DM,
    CODE_059_ACCESS_DENIED_TO_DM,

    CODE_060_HTTP_CONTENT_TYPE_NOT_SUPPORTED,

    CODE_061_WRONG_PARAMETERS_FOR_CORE,

    CODE_062_ALREADY_LOGGED_IN_WITH_DIFFERENT_USERNAME,

    CODE_063_ACCESS_DENIED_TO_AC,

    CODE_062_UR_ASSIGNMENTS_ALREADY_EXISTS,
    CODE_063_PA_ASSIGNMENTS_ALREADY_EXISTS,

    CODE_064_DELETE_ATTRIBUTES_CAUSES_EMPTY_ACCESS_STRUCTURE,
    CODE_065_ATTRIBUTE_ALREADY_EXISTS,
    CODE_066_ATTRIBUTE_NOT_FOUND,
    CODE_067_ATTRIBUTE_WAS_DELETED,
    CODE_068_ATTRIBUTETUPLE_ALREADY_EXISTS,
    CODE_069_ACCESSSTRUCTURETUPLE_ALREADY_EXISTS,
    CODE_070_ATTRIBUTETUPLE_NOT_FOUND,
    CODE_071_ACCESSSTRUCTURETUPLE_NOT_FOUND,
    CODE_072_MPK_ALREADY_INITIALIZED,
    CODE_073_ABE_KEY_NOT_FOUND,
    CODE_074_CANNOT_REVOKE_LAST_ACCESS_STRUCTURE_TUPLE,

    CODE_075_DM_CONFIGURATION,
    CODE_076_OPA_POLICY_EVAL,

    CODE_077_SERVICE_ALREADY_CONFIGURED,

    CODE_078_XACML_CONFIGURATION,
    CODE_079_XACML_DOMAIN_QUERY,
    CODE_080_XACML_PAP,
    CODE_081_XACML_PAP_POLICY_NOT_FOUND,
    CODE_082_XACML_PDP,
    CODE_083_XACML_PDP_UNAUTHORIZED,

    CODE_084_UNSUPPORTED_DYNSEC_ERROR;



    /**
     * Parse this code to extract the error number.
     * For instance, "CODE_047_UNEXPECTED".getNumber()
     * returns "047"
     */
    fun getNumber() = this.toString().split("_")[1]

    /**
     * Parse this code to extract the error message.
     * For instance, "CODE_046_HTTP_METHOD_NOT_SUPPORTED".getMessage()
     * returns "HTTP METHOD NOT SUPPORTED"
     */
    fun getMessage() = this.toString().split("_").toMutableList().filterIndexed { index, _ ->
        index != 0 && index != 1
    }.joinToString(separator = " ")
}
