package eu.fbk.st.cryptoac

import kotlinx.serialization.Serializable

/**
 * Codes for describing the outcome of any operation in CryptoAC.
 * A code is composed of the keyword "CODE", the error number and
 * an error message, separated by the underscore "_" character.
 * If none of these codes is suitable to describe the outcome of
 * a new operation, document and add a new code
 */
@Serializable
enum class OutcomeCode {
    CODE_000_SUCCESS,
    
    CODE_001_USER_ALREADY_EXISTS,
    CODE_002_ROLE_ALREADY_EXISTS,
    CODE_003_FILE_ALREADY_EXISTS,
    
    CODE_004_USER_NOT_FOUND,
    CODE_005_ROLE_NOT_FOUND,
    CODE_006_FILE_NOT_FOUND,

    CODE_007_ROLETUPLE_NOT_FOUND,
    CODE_008_PERMISSIONTUPLE_NOT_FOUND,
    CODE_009_FILETUPLE_NOT_FOUND,

    CODE_010_ROLETUPLE_ALREADY_EXISTS,
    CODE_011_PERMISSIONTUPLE_ALREADY_EXISTS,
    CODE_012_FILETUPLE_ALREADY_EXISTS,

    CODE_013_USER_WAS_DELETED,
    CODE_014_ROLE_WAS_DELETED,
    CODE_015_FILE_WAS_DELETED,

    CODE_016_INVALID_PERMISSION,
    CODE_017_INVALID_VERSION_NUMBER,

    CODE_018_INTERFACE_CONFIGURATION_PARAMETERS,
    CODE_019_MISSING_PARAMETERS,
    CODE_020_INVALID_PARAMETER,
    CODE_021_RM_CONFIGURATION,

    CODE_022_ADMIN_CANNOT_BE_MODIFIED,
    CODE_023_USER_CANNOT_BE_MODIFIED,

    CODE_024_FILE_DELETE,
    CODE_025_FILE_RENAMING,

    CODE_026_TUPLE_FORMAT,
    CODE_027_AC_ENFORCEMENT_INCONSISTENT,

    CODE_028_OPA_POLICY_CREATION,
    CODE_029_OPA_DOCUMENT_UPDATE,
    CODE_030_OPA_DOCUMENT_DOWNLOAD,

    CODE_031_LOCK_CALLED_IN_INCONSISTENT_STATUS,
    CODE_032_UNLOCK_CALLED_IN_INCONSISTENT_STATUS,
    CODE_033_ROLLBACK_CALLED_IN_INCONSISTENT_STATUS,
    CODE_034_UNLOCK_FAILED,

    CODE_035_ADMIN_ALREADY_INITIALIZED,
    CODE_036_ADMIN_NAME,
    
    CODE_037_FORBIDDEN,
    CODE_038_UNAUTHORIZED,

    CODE_039_PROFILE_NOT_FOUND,
    CODE_040_MALFORMED_PROFILE_FILE,

    CODE_041_UR_ASSIGNMENTS_NOT_FOUND_OPA,
    CODE_042_PA_ASSIGNMENTS_NOT_FOUND_OPA,

    CODE_043_RM_CONNECTION_TIMEOUT,
    CODE_044_DM_CONNECTION_TIMEOUT,
    CODE_045_MM_CONNECTION_TIMEOUT,
    CODE_046_CRYPTOAC_CONNECTION_TIMEOUT,
    CODE_047_OPA_CONNECTION_TIMEOUT,

    CODE_048_HTTP_METHOD_NOT_SUPPORTED,

    CODE_049_UNEXPECTED,

    CODE_050_FUNCTIONALITY_UNDER_CONSTRUCTION,

    CODE_051_LOGIN_REQUIRED,

    CODE_052_USER_ALREADY_INITIALIZED,
    CODE_053_USER_IS_INCOMPLETE,

    CODE_054_CREATE_USER_MM,
    CODE_055_ACCESS_DENIED_TO_MM,
    CODE_056_DELETE_USER_MM,

    CODE_057_INTERFACE_TYPE_UPDATED,

    CODE_058_INCONSISTENT_STATUS_DELETE_TEMPORARY_FILE_IN_DM,
    CODE_059_ACCESS_DENIED_TO_DM,

    CODE_060_HTTP_CONTENT_TYPE_NOT_SUPPORTED;




    /**
     * Parse this code to extract the error number.
     * For instance, "CODE_047_UNEXPECTED".getNumber()
     * returns "047"
     */
    fun getNumber() = this.toString().split("_")[1]

    /**
     * Parse this code to extract the error message.
     * For instance, "CODE_046_HTTP_METHOD_NOT_SUPPORTED".getMessage()
     * returns "HTTP METHOD NOT SUPPORTED"
     */
    fun getMessage() = this.toString().split("_").toMutableList().filterIndexed { index, _ ->
        index != 0 && index != 1
    }.joinToString(separator = " ")
}