version: '3'
services:
  proxy:
    build:
      context: .
      dockerfile: DockerfileCryptoAC
    entrypoint: [ "java", "-jar", "/cryptoac/CryptoAC.jar", "-op", "-p", "${CRYPTOACPROXYPROXYPORT}"]
    ports:
      - "${CRYPTOACPROXYHOSTPORT}:${CRYPTOACPROXYPROXYPORT}"
  rm:
    build:
      context: .
      dockerfile: DockerfileCryptoAC
    entrypoint: [ "java", "-jar", "/cryptoac/CryptoAC.jar", "-or", ms, "${CRYPTOACMSPASSWORDFORRM}", "${CRYPTOACMSMSPORT}", "${CRYPTOACMSUSERNAMEFORRM}", ds, "${CRYPTOACDSPORT}", "-p", "${CRYPTOACRMPORT}"]
  ds:
    build:
      context: .
      dockerfile: DockerfileCryptoAC
    entrypoint: [ "java", "-jar", "/cryptoac/CryptoAC.jar", "-od", "-p", "${CRYPTOACDSPORT}"]
  ms:
    build:
      context: .
      dockerfile: DockerfileMySQL
    environment:
      MYSQL_ROOT_PASSWORD: "${CRYPTOACMSPASSWORDFORRM}"
    ports:
      - "${CRYPTOACMSHOSTPORT}:${CRYPTOACMSMSPORT}"