docker rm -f installation_cryptoac_mosquitto_1 installation_cryptoac_mysql_1 installation_cryptoac_opa_1 installation_cryptoac_proxy_1 installation_cryptoac_rm_1 installation_cryptoac_ds_1

docker rmi -f cryptoac_mosquitto cryptoac_mysql cryptoac_opa cryptoac_cryptoac