version: '3'
services:

  cryptoac_proxy:
    networks:
      test:
        ipv4_address: "${CRYPTOACPROXYHOSTIP}"
    image: cryptoac_cryptoac:latest
    ports:
      - "${CRYPTOACPROXYHOSTPORT}:${CRYPTOACPROXYPROXYPORT}"
    entrypoint: [ "/cryptoac/bin/CryptoAC", "-op"]

  cryptoac_rm:
    networks:
      test:
        ipv4_address: "${CRYPTOACRMHOSTIP}"
    image: cryptoac_cryptoac:latest
    ports:
      - "${CRYPTOACRMHOSTPORT}:${CRYPTOACRMHOSTPORT}"
    entrypoint: [ "/cryptoac/bin/CryptoAC", "-or"]

  cryptoac_ds:
    networks:
      test:
        ipv4_address: "${CRYPTOACDSHOSTIP}"
    image: cryptoac_cryptoac:latest
    ports:
      - "${CRYPTOACDSHOSTPORT}:${CRYPTOACDSHOSTPORT}"
    entrypoint: [ "/cryptoac/bin/CryptoAC", "-od"]

  cryptoac_mysql:
    networks:
      test:
        ipv4_address: "${CRYPTOACMYSQLHOSTIP}"
    image: cryptoac_mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${CRYPTOACMYSQLPASSWORD}"
    ports:
      - "${CRYPTOACMYSQLHOSTPORT}:${CRYPTOACMYSQLMYSQLPORT}"
      
  cryptoac_opa:
    networks:
      test:
        ipv4_address: "${CRYPTOACOPAHOSTIP}"
    image: cryptoac_opa:latest
    ports:
      - "${CRYPTOACOPAPORT}:${CRYPTOACOPAPORT}"
    # WARNING: OPA is NOT running with an authorization policy configured. This
    # means that clients can read and write policies in OPA. If you are
    # deploying OPA in an insecure environment, be sure to configure
    # authentication and authorization on the daemon. See the Security page for
    # details: https://www.openpolicyagent.org/docs/security.html.
    command:
    - "run"
    - "--server"
    - "--log-format=json-pretty"
    - "--set=decision_logs.console=true"
networks:
  test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24