version: '3'
services:
  cryptoac_proxy:
    networks:
      test:
        ipv4_address: "${CRYPTOACPROXYHOSTIP}"
    image: cryptoac_cryptoac:latest
    ports:
      - "${CRYPTOACPROXYHOSTPORT}:${CRYPTOACPROXYPROXYPORT}"
  cryptoac_mosquitto:
    networks:
      test:
        ipv4_address: "${CRYPTOACMOSQUITTOHOSTIP}"
    image: cryptoac_mosquitto:latest
    ports:
      - "${CRYPTOACMOSQUITTOHOSTPORT}:${CRYPTOACMOSQUITTOMOSQUITTOPORT}"
  cryptoac_redis:
    networks:
      test:
        ipv4_address: "${CRYPTOACREDISHOSTIP}"
    image: cryptoac_redis:latest
    ports:
      - "${CRYPTOACREDISHOSTPORT}:${CRYPTOACREDISPORT}"
networks:
  test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24




