version: '3'
services:

  cryptoac_proxy:
    networks:
      test:
        ipv4_address: "${CRYPTOACPROXYHOSTIP}"
    image: cryptoac_cryptoac:latest
    ports:
      - "${CRYPTOACPROXYHOSTPORT}:${CRYPTOACPROXYPROXYPORT}"
    entrypoint: [ "/cryptoac/bin/CryptoAC", "-op"]

networks:
  test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24